# Configuración del clúster Mesh entre múltiples routers (Distribución)
upstream chrono_mesh_network {
    server 127.0.0.1:5000 weight=3; # Nodo Local Core
    # server 192.168.1.100:5000;    # Router Peer 02 (Mesh Nodo)
    # server 192.168.1.101:5000;    # Router Peer 03 (Mesh Nodo)
}

server {
    listen 8080;
    server_name _;

    root /www/chronoshield;
    index index.html;

    # Hardening: Unidades Inmutables de Solo Lectura
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Content-Security-Policy "default-src 'self';" always;

    location /api/ {
        proxy_pass http://chrono_mesh_network;
        proxy_set_header Host $host;
        proxy_set_header Authorization "Bearer CS_ONION_PERIMETER_SECURE_TOKEN_2026";
        
        # Simulación de mTLS: Validación estricta requerida en producción
        proxy_set_header X-SSL-Client-Verify "SUCCESS";
    }

    # Endpoint expuesto para el colector central de Prometheus
    location /metrics {
        allow 127.0.0.1; 
        # allow 10.0.0.0/24; # Red interna de Grafana/Prometheus (Escalabilidad)
        deny all;
        proxy_pass http://127.0.0.1:5000/metrics;
    }
}
